### ISSUE TITLE
Difference in "bun link" and usage command from README.md

### ISSUE THREAD

**Issue by brokoli777** [Kannav02/DialectMorph#1]
When linking, the readme instructions say:

![image](https://github.com/user-attachments/assets/2a42fe1c-90ed-41a5-8dab-b3e611d5e9d5)

But the command for running is:

![image](https://github.com/user-attachments/assets/6cb10575-27e2-4a6f-acf0-e9327352e4c2)

Resulting in:
![image](https://github.com/user-attachments/assets/c063b3c6-5369-4519-93f8-3900d8f3ce2f)

**Comment by Kannav02** [comment]
I got that issue as well
Its usually concerning with the the .bun/bin not being in PATH variable, 

the steps to fix this would be the following 

1) export the bun binary to the path variable
```
export PATH="/Users/username/.bun/bin:$PATH"
```
2) reload the zshrc file
```
source ~/.zshrc
```
3) try running the following command to see if the binary exists 

```
which dialectMorph
```
I should add this to the README.md file


Thank you for reporting this issue

**Comment by Kannav02** [comment]
I have added the information in the README.md file that should assist in fixing the error
