### ISSUE TITLE
Add a link to show users where to install bun

### ISSUE THREAD

**Issue by peterdanwan** [Kannav02/DialectMorph#15]
Hello! I was following your documentation and thought we should link the [bun installation guide](https://bun.sh/docs/installation), just in case `DialectMorph` users don't have this program on their systems already.

I can add a link that shows how to install `bun` to your README.md file and can edit the wording if needed!

**Comment by Kannav02** [comment]
Thank you for pointing this out, I somehow missed this 

PR #16 will fix this
