### ISSUE TITLE
.gitignore the generated transpiledFiles folder and update README.md

### ISSUE THREAD

**Issue by peterdanwan** [Kannav02/DialectMorph#19]
Hello @Kannav02!

I was hoping to perhaps update your README.md's [Optional Arguments section](https://github.com/Kannav02/DialectMorph#optional-arguments) with a description of how your `-t` / `--token` works.

In addition, I thought that perhaps we could update your `.gitignore` file to ignore the `transpiledFiles` folder as well. This way, we can reduce the risk of other contributors accidentally including files within the `transpiledFiles` folder in their commits.

![transpiledFiles-folder](https://github.com/user-attachments/assets/7ffb57db-3c4f-4c7a-aee8-99e23809b631)

**Comment by Kannav02** [comment]
sure! that would be helpful!

thank you!
