### ISSUE TITLE
Addition: Support using a TOML "dotfile" file to configure the tool's options

### ISSUE THREAD

**Issue by arilloid** [Kannav02/DialectMorph#24]
Hello @Kannav02 

It would be beneficial to add support for configuring dialectMorph using `.toml` configuration files.

This way, the users will be able to specify their preferred options all in one place (`.toml` file stored in their home directory) instead of having to pass them as command-line arguments.

The contents of the config file can be parsed using `toml` library, and then merged with the provided command-line options (the passed arguments will take precedence overriding the default config options).

I would love to work on this issue!

**Comment by Kannav02** [comment]
Merged #25 into the main branch, thank you for the help!
